name: Publish to NPM

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies for zemcp-mssql
        run: |
          cd zemcp-mssql
          npm ci

      - name: Build zemcp-mssql
        run: |
          cd zemcp-mssql
          npm run build

      - name: Publish zemcp-mssql to NPM
        run: |
          cd zemcp-mssql
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install dependencies for zemcp-oracle
        run: |
          cd zemcp-oracle
          npm ci

      - name: Build zemcp-oracle
        run: |
          cd zemcp-oracle
          npm run build

      - name: Publish zemcp-oracle to NPM
        run: |
          cd zemcp-oracle
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
